"""Числовые коды error_code в сообщениях протокола (wire)."""

from __future__ import annotations

from protocol.types import Level, Status

WIRE_APP_CONFIG = 8101
WIRE_APP_CMD_BLOCKED = 8102
WIRE_APP_CMD_BUILD = 8103
WIRE_APP_CONNECT_FIELDS = 8104
WIRE_APP_INPUT_FIELD = 8105

WIRE_LINK_CONNECTING = 1001
WIRE_LINK_READY = 1002
WIRE_LINK_LOST = 1003
WIRE_LINK_CMD_NO_CONN = 1004
WIRE_LINK_CMD_PONG = 1005
WIRE_LINK_DISCONNECTED = 1006

WIRE_PROTO_JSON = 2001
WIRE_PROTO_EMPTY = 2002
WIRE_PROTO_NOT_OBJECT = 2003
WIRE_PROTO_VALIDATION = 2004
WIRE_PROTO_UNEXPECTED_CMD = 2005
WIRE_PROTO_UNKNOWN_TYPE = 2006

WIRE_CMD_TIMEOUT = 3001
WIRE_CMD_ORPHAN = 3002
WIRE_CMD_ACCEPTED = 3003
WIRE_CMD_REJECTED = 3004
WIRE_CMD_ERROR = 3005

WIRE_ACT_LOADED = 4001
WIRE_ACT_FAILED = 4002
WIRE_ACT_EMPTY = 4003
WIRE_ACT_TIMEOUT = 4004
WIRE_ACT_INVALID = 4005
WIRE_ACT_SEND_UNAVAILABLE = 4006

WIRE_TEL_VALIDATION = 5001

WIRE_TRN_NOT_CONNECTED = 6001
WIRE_TRN_MODULE_MISSING = 6002
WIRE_TRN_IO = 6003
WIRE_TRN_INVALID_SOCKET = 6004
WIRE_TRN_MQTT_PUBLISH = 6005

WIRE_CTRL_INFO = 7001
WIRE_CTRL_WARN = 7002
WIRE_CTRL_ERROR = 7003


def wire_code_for_response_status(status: Status) -> int:
    if status in (Status.ACCEPTED, Status.COMPLETED):
        return WIRE_CMD_ACCEPTED
    if status == Status.REJECTED:
        return WIRE_CMD_REJECTED
    return WIRE_CMD_ERROR


def wire_code_for_diagnostic_level(level: Level) -> int:
    if level == Level.ERROR:
        return WIRE_CTRL_ERROR
    if level == Level.WARNING:
        return WIRE_CTRL_WARN
    return WIRE_CTRL_INFO
